export const ROLES = ["Admin", "Staff", "Customer"];

export const initialUsers = [
  {
    id: 1,
    name: "James Wilson",
    email: "james.wilson@example.com",
    role: "Admin",
    joined: "Oct 12, 2023",
    status: "Active",
    avatar: null, // null = show initials fallback
    initials: "JW",
    color: "#4f46e5",
  },
  {
    id: 2,
    name: "Sarah Jenkins",
    email: "s.jenkins@ecoffee.com",
    role: "Staff",
    joined: "Jan 05, 2024",
    status: "Active",
    avatar: null,
    initials: "SJ",
    color: "#0891b2",
  },
  {
    id: 3,
    name: "Michael Chen",
    email: "mchen92@gmail.com",
    role: "Customer",
    joined: "Feb 14, 2024",
    status: "Suspended",
    avatar: null,
    initials: "MC",
    color: "#059669",
  },
  {
    id: 4,
    name: "Linda Rodriguez",
    email: "linda.r@webmail.com",
    role: "Customer",
    joined: "Mar 01, 2024",
    status: "Active",
    avatar: null,
    initials: "LR",
    color: "#d97706",
  },
  {
    id: 5,
    name: "Tom Baker",
    email: "tombaker@mail.com",
    role: "Staff",
    joined: "Apr 10, 2024",
    status: "Active",
    avatar: null,
    initials: "TB",
    color: "#7c3aed",
  },
  {
    id: 6,
    name: "Anna Lee",
    email: "anna.lee@ecoffee.com",
    role: "Customer",
    joined: "May 20, 2024",
    status: "Active",
    avatar: null,
    initials: "AL",
    color: "#db2777",
  },
  {
    id: 7,
    name: "David Kim",
    email: "dkim@example.com",
    role: "Customer",
    joined: "Jun 03, 2024",
    status: "Suspended",
    avatar: null,
    initials: "DK",
    color: "#ea580c",
  },
  {
    id: 8,
    name: "Maria Gomez",
    email: "mgomez@ecoffee.com",
    role: "Admin",
    joined: "Jul 15, 2024",
    status: "Active",
    avatar: null,
    initials: "MG",
    color: "#16a34a",
  },
  {
    id: 9,
    name: "Chris Patel",
    email: "cpatel@gmail.com",
    role: "Customer",
    joined: "Aug 22, 2024",
    status: "Active",
    avatar: null,
    initials: "CP",
    color: "#0284c7",
  },
  {
    id: 10,
    name: "Fiona Walsh",
    email: "fwalsh@webmail.com",
    role: "Staff",
    joined: "Sep 01, 2024",
    status: "Active",
    avatar: null,
    initials: "FW",
    color: "#9333ea",
  },
  {
    id: 11,
    name: "Ryan Nguyen",
    email: "rnguyen@ecoffee.com",
    role: "Customer",
    joined: "Sep 14, 2024",
    status: "Active",
    avatar: null,
    initials: "RN",
    color: "#b45309",
  },
  {
    id: 12,
    name: "Sophie Turner",
    email: "sturner@example.com",
    role: "Customer",
    joined: "Oct 05, 2024",
    status: "Suspended",
    avatar: null,
    initials: "ST",
    color: "#0f766e",
  },
];
